package org.lafeuille.demo.infra.cassandra

import org.lafeuille.demo.infra.data.InfraDataConfiguration
import org.springframework.context.annotation.Configuration
import org.springframework.data.cassandra.config.EnableReactiveCassandraAuditing

@Configuration
@EnableReactiveCassandraAuditing(dateTimeProviderRef = InfraDataConfiguration.BeanNames.DATE_TIME_PROVIDER_NAME)
class InfraDataCassandraConfiguration