[versions]
gorylenko-git-properties = "4.0.1"
mockito-kotlin = "6.3.0"
spotless = "8.8.0"
spring-boot = "4.1.0"
spring-cloud = "2025.1.2"
spring-dependency-management = "1.1.7"
spring-modulith = "2.1.0"

[plugins]
gorylenko-git-properties = { id = "com.gorylenko.gradle-git-properties", version.ref = "gorylenko-git-properties" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
