name: Gradle Publish Boot Jar

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish-boot-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
      - name: Publish to Github Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pversion=${{ inputs.version }} bootBuildImage --publishImage
          env:
            USERNAME: ${{ github.actor }}
            TOKEN: ${{ secrets.GITHUB_TOKEN }}
