name: Gradle Publish Boot Jar

on:
  workflow_call:
    inputs:
      artifact-version:
        required: true
        type: string
      java-distribution:
        type: string
        default: 'temurin'
      java-version:
        type: string
        default: '21'

jobs:
  publish-boot-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: 'gradle'
      - uses: gradle/actions/setup-gradle@v4
      - name: Publish to Github Packages
        run: gradle -Pversion=${{ inputs.artifact-version }} bootBuildImage --publishImage
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
